name: Update Playlist Tokens
on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and browsers
        run: |
          pip install playwright PyYAML
          # Установка самого браузера Chromium и системных библиотек Linux
          playwright install --with-deps chromium

      - name: Run grabber script
        run: python grabber.py
        env:
          LOGIN: ${{ secrets.SMOTRET_LOGIN }}
          PASSWORD: ${{ secrets.SMOTRET_PASSWORD }}

      - name: Commit and Push M3U file
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add playlist_928374hfkj.m3u
          # Если изменений нет, просто пропускаем коммит
          git commit -m "Update playlist tokens $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
