name: Grab Playlist with Edge
on:
  workflow_dispatch: # Запуск вручную кнопкой
  schedule:
    - cron: '0 0 * * *' # Раз в сутки

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          # Устанавливаем браузеры и их системные зависимости
          playwright install msedge
          sudo playwright install-deps

      - name: Run Script in Virtual Display
        run: |
          # xvfb-run создает виртуальный монитор, позволяя headless=False работать на сервере
          xvfb-run python your_script_name.py

      - name: Commit and Push Playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "Update playlist" || echo "No changes"
          git push

