name: Edge Playlist Grabber
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов

jobs:
  run-grabber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          python -m playwright install msedge
          sudo python -m playwright install-deps msedge

      - name: Run Scraper in Virtual Display
        run: xvfb-run python grabber.py

      - name: Commit and Push
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Update playlist" || exit 0
          git push


