name: Chrome Playlist Grabber
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-grabber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright and Chrome
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          # Установка самого Chrome
          python -m playwright install chrome
          # Установка системных зависимостей для работы GUI Chrome
          sudo $(which python) -m playwright install-deps chrome

      - name: Run Scraper in Virtual Display
        run: xvfb-run python grabber.py

      - name: Commit and Push
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Update playlist (Chrome)" || exit 0
          git push



