name: Playlist Grabber
on:
  workflow_dispatch: # Кнопка ручного запуска
  schedule:
    - cron: '0 */6 * * *' # Автозапуск каждые 6 часов

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Playwright Browsers
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-chromium-${{ runner.os }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright Chromium
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: python -m playwright install chromium --with-deps

      - name: Install System Dependencies
        run: |
          # Исправляем ошибку No module named playwright под sudo
          sudo $(which python) -m playwright install-deps chromium

      - name: Run Scraper
        run: python grabber.py # Убедись, что твой скрипт называется grabber.py

      - name: Commit and Push Playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "Update playlist: $(date)" || echo "No changes"
          git push
